LogisticRegression:
  l1_ratio: 0.7
  

KNeighborsClassifier:
  n_neighbors: 5


# GaussianNB:
#   var_smoothing: float, default=1e-9

DecisionTreeClassifier:
  criterion: "log_loss"
  max_depth: 8

RandomForestClassifier:
  n_estimators: 
   - 100
   - 200
   - 300
  max_depth: 
   - None
   - 5
   - 10
  min_samples_split: 
   - 2
   - 5
   - 10
  min_samples_leaf: 
   - 1
   - 2
   - 4


SVC:
  C:
   - 0.1
   - 1
   - 10
  kernel: 
   - linear
   - rbf
  gamma: 
   - 0.1
   - 0.01
   - 0.001

GradientBoostingClassifier:
  n_estimators:
   - 100
  criterion:
   - friedman_mse