LogisticRegression:
  penalty:
    - l1
    - l2
  C:
    - 0.1
    - 0.5
    - 1.0
  solver:
    - newton-cg
    - lbfgs
    - liblinear
    - sag


GaussianNB:
  var_smoothing:
    - 1e-9
    - 1e-8
    - 1e-7

KNeighborsClassifier:
  n_neighbors: 
    - 3
    - 5
    - 7

DecisionTreeClassifier:
  criterion: 
    - "gini"
    - "entropy"
  max_depth: 
    - 6
    - 8
    - 10

RandomForestClassifier:
  n_estimators: 
    - 100
    - 200
    - 300
  max_depth: 
    - None
    - 5
    - 10
  min_samples_split: 
    - 2
    - 5
    - 10
  min_samples_leaf: 
    - 1
    - 2
    - 4

SVC:
  C:
    - 0.1
    - 1
    - 10
  kernel: 
    - linear
    - rbf
  gamma: 
    - 0.1
    - 0.01
    - 0.001

GradientBoostingClassifier:
  n_estimators:
    - 50
    - 100
    - 150
  criterion:
    - friedman_mse
    - mse
    - mae