artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/CC-KEH/Datasets_For_ML/raw/main/heart.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/heart.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/heart.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv
